### ISSUE TITLE
Integrate Falsk-RESTPlus

### ISSUE THREAD

**Issue by dmi3coder** [donautech/behaiv-remote-kernel#1]
We need to generate openapi/swagger file based on our python api, later on we can use it in both ios, android, web clients with auto-generation(before we'll switch to protobuf)

**Comment by sagarkar10** [comment]
I will be interested in picking this up...

**Comment by dmi3coder** [comment]
@sagarkar10 I'll appreciate it! I've found one article that can help http://michal.karzynski.pl/blog/2016/06/19/building-beautiful-restful-apis-using-flask-swagger-ui-flask-restplus/
though there's almost no API as of now, I'll add some more endpoints tomorrow.
Later on, I would like to connect this api with client project: https://github.com/dmi3coder/behaiv-java
Thank you for interest :) Let me know if you need any info or help

**Comment by sagarkar10** [comment]
Thank. I would like to know the exact details of the api, i know how to implement them. But please tell me what interaction it is supposed to make so that i can start.

**Comment by dmi3coder** [comment]
@sagarkar10 What we need is to generate yaml/json file that will describe the API when server is running. Ideally API should have [swagger ui](https://swagger.io/tools/swagger-ui/) on `/api/` endpoint as well as .yaml file serving somewhere (e.g `/api/openapi.yaml`). 
No additional work required for now. Later when we'll need to add more endpoints it'll automatically generate fresh yaml file

**Comment by sagarkar10** [comment]
Can you explain a little more! @dmi3coder

**Comment by dmi3coder** [comment]
Yes sure. So, We have api that needs to be exposed with documentation to public. https://github.com/noirbizarre/flask-restplus is a perfect way to expose API. Basically what it does is that it documents each endpoint that's declared in our api. 
So, for example, if i'll declare:
```python
@bp.route('/store/inventory')
def get():
    return whatever
```
swagger will generate me something like this in swagger.yaml
```
/store/inventory:
    get:
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
      security:
      - api_key: []
```
I've found that https://github.com/noirbizarre/flask-restplus is a good solution for that. We'll need to use object-oriented style for endpoints and that's okay.
So, the requirement is only to add this library and wrap blueprints so they'll have access to it. 
Here's how to integrate swagger on their docs https://flask-restplus.readthedocs.io/en/latest/swagger.html#swaggerui

**Comment by dmi3coder** [comment]
There's also https://github.com/gangverk/flask-swagger that can extract docstrings, that's also one option, easier to implement, though we'll need to document each endpoint in the docstring

**Comment by sagarkar10** [comment]
Will go with either of them and put a pr. Where are the apis defined. Please point me.

**Comment by dmi3coder** [comment]
It's in each of the packages e.g https://github.com/donautech/behaiv-remote-kernel/tree/master/app/client or https://github.com/donautech/behaiv-remote-kernel/blob/master/app/config named `routes.py` (almost all of them are empty). I'll add some more endpoints shortly, firstly want to finish next 0.4 release for java version

**Comment by dmi3coder** [comment]
@sagarkar10 I've made Pr with some endpoints.
Let me know if you're still up to this task or should I take it
I think we can go with second option, it'll be faster to integrate. https://github.com/gangverk/flask-swagger
