### ISSUE TITLE
Wrap Flask into docker. Dockerize application

### ISSUE THREAD

**Issue by dmi3coder** [donautech/behaiv-remote-kernel#12]
We need to wrap flask into docker. 
We need to firstly build `./client` folder with script similar to `./client_dev.sh` and add everything needed

**Comment by Zoxon470** [comment]
I will solve this issue

**Comment by Zoxon470** [comment]
Check my pull request https://github.com/donautech/behaiv-remote-kernel/pull/15

**Comment by dmi3coder** [comment]
Great job, thank you!
